-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_INFO a, REST_REVIEW b
WHERE a.REST_ID = b.REST_ID and ADDRESS LIKE '서울%'
GROUP BY a.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY AVG(REVIEW_SCORE) desc, FAVORITES desc

