-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(a.PRICE * AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT a, FOOD_ORDER b
WHERE a.PRODUCT_ID = b.PRODUCT_ID 
    AND '2022-05' = to_char(b.PRODUCE_DATE, 'yyyy-mm')
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC