-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO a, FISH_NAME_INFO b
WHERE a.FISH_TYPE = b.FISH_TYPE
    and (a.FISH_TYPE, a.LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )
ORDER BY ID asc